### ISSUE TITLE
The Minskins 01/07 Review

### ISSUE THREAD

**Issue by Bismarck-GM** [carlosveigadev/Bubble-Sort-Microverse#2]
Great work sorting the bubble!

Here you got a beaver... he's always watching... 👀 

<pre>
       (\.---./)    
        /.-.-.\
       /| 0_0 |\
      |_`-(v)-'_|
      \`-._._.-'/      .-.
-~-(((.`-\_|_/-'.)))-~' <_
       `.     .'
         `._.'
-----~--~---~~~----~-`.-;~
</pre>

**Comment by layzrd** [comment]
Thanks @Bismarck-GM
